# Credits due: by https://dusted.codes/github-actions-for-dotnet-core-nuget-packages#branch-and-pull-request-trigger

name: .NET Core

on:
  push:
  pull_request:
  release:
    types:
      - published
    
env:
  # Stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  # GitHub Packages Feed settings
  GITHUB_FEED: https://nuget.pkg.github.com/koenbeuk/
  GITHUB_USER: koenbeuk
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # Official NuGet Feed settings
  NUGET_FEED: https://api.nuget.org/v3/index.json
  NUGET_KEY: ${{ secrets.NUGET_KEY }}
  
jobs:
  build-v1:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on:  ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Install dependencies
        run: dotnet restore EntityFrameworkCore.Triggered.sln -p:Configuration=ReleaseV1
      - name: Build
        run: dotnet build --configuration ReleaseV1 --no-restore EntityFrameworkCore.Triggered.sln
      - name: Test
        run: dotnet test --configuration ReleaseV1 --verbosity normal EntityFrameworkCore.Triggered.sln
      - name: Pack
        if: matrix.os == 'ubuntu-latest'
        run: | 
          dotnet pack -v normal -c ReleaseV1 --include-symbols --include-source -p:PackageVersion=$GITHUB_RUN_ID -o nupkg EntityFrameworkCore.Triggered.Core-v1.slnf
      - name: Upload Artifact
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v2
        with:
          name: nupkg
          path: ./nupkg/*.nupkg
  
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on:  ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Install dependencies
        run: dotnet restore EntityFrameworkCore.Triggered.sln -p:Configuration=Release
      - name: Build
        run: dotnet build --configuration Release --no-restore EntityFrameworkCore.Triggered.sln
      - name: Test
        run: dotnet test --configuration Release --verbosity normal EntityFrameworkCore.Triggered.sln
      - name: Pack
        if: matrix.os == 'ubuntu-latest'
        run: | 
          dotnet pack -v normal -c Release --include-symbols --include-source -p:PackageVersion=2.0.0-pre-$GITHUB_RUN_ID -o nupkg EntityFrameworkCore.Triggered.Core.slnf
      - name: Upload Artifact
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v2
        with:
          name: nupkg
          path: ./nupkg/*.nupkg
  
  build-samples:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on:  ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Install dependencies
        run: dotnet restore EntityFrameworkCore.Triggered.Samples.slnf
      - name: Build
        run: dotnet build --configuration Release --no-restore  EntityFrameworkCore.Triggered.Samples.slnf
        
  prerelease:
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v1
        with:
          name: nupkg
      - name: Push to GitHub Feed
        run: |
          for f in ./nupkg/*.nupkg
          do
            dotnet nuget push $f --source $GITHUB_FEED --api-key ${{github.token}} --skip-duplicate --no-symbols true
          done
          
  deploy:
    needs: [build, build-v1]
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Create Release NuGet package
        run: |
          arrTag=(${GITHUB_REF//\// })
          VERSION="${arrTag[2]}"
          echo Version: $VERSION
          CONFIGURATION=$([ "${VERSION:0:2}" == "v1" ] && echo "ReleaseV1" || echo "Release")
          VERSION="${VERSION//v}"
          echo Clean Version: $VERSION
          echo Configuration: $CONFIGURATION
          dotnet pack -v normal -c $CONFIGURATION --include-symbols --include-source -p:PackageVersion=$VERSION -o nupkg EntityFrameworkCore.Triggered.Core.slnf
      - name: Push to GitHub Feed
        run: |
          for f in ./nupkg/*.nupkg
          do
            dotnet nuget push $f --source $GITHUB_FEED --api-key ${{github.token}} --skip-duplicate --no-symbols true
          done
      - name: Push to NuGet Feed
        run: |
          for f in ./nupkg/*.nupkg
          do
            dotnet nuget push $f --source $NUGET_FEED --skip-duplicate --api-key $NUGET_KEY
          done
